services:
  postgres:
    image: postgres:17-alpine
    container_name: operaty-ai-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-script:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
